version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_saas
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mynetwork

  Appointment.Backend:
    image: appointment-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AppointmentProjectDefaultString=${AppointmentProjectDefaultString}
    ports:
      - "5000:80"
    depends_on:
      - mssql
    networks:
      - mynetwork

volumes:
  mssql_data:

networks:
  mynetwork:
